language: node_js
node_js:
- '8'
sudo: true
dist: trusty
env:
- MSGFLO_BROKER=mqtt://localhost
before_install:
- sudo apt-get update -qq
- sudo apt-get install pkg-config libev-dev cmake openssl libc-ares-dev
install:
- export CC=gcc-4.8
- export CXX=g++-4.8
- wget http://mosquitto.org/files/source/mosquitto-1.3.1.tar.gz
- tar xzf mosquitto-1.3.1.tar.gz
- cd mosquitto-1.3.1
- cmake .
- sudo make install
- cd ..
- npm install
- curl -sSL https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz | tar -xzC
  ./
- export PATH=`pwd`/cmake-3.5.2-Linux-x86_64/bin:$PATH
- which cmake
- cd dlock13-msgflo
- "./build.sh"
- cd -
- pip install --user nose twine
- pip install --user -r requirements.txt
- pip install --user -r test/requirements.txt
before_script:
- mosquitto -d
script:
- npm test
- nosetests -v
deploy:
  provider: pypi
  user: jonnor
  skip_upload_docs: true
  password:
    secure: OYWE0XXYZ6loHhlQbSLTLAGUgjfNp2a2sf+zjmD5IrD4f/FM/bGL5AlLv3RvjW+bY+T7f4iYBwfJC1/bC5/7HIcpQGRFZ9YgTFg0nGENHHnvpo24XWrXdj0N4mDbILsu093S3iIh86D9BCPsPGmpRm4Kfzajy8FfT0NeaIsJgp0=
  on:
    tags: true
    repo: bitraf/dlock13
