#!/usr/bin/env python2

import dlock13

import sys, time

def open(topic, duration):
    name = 'nada'
    doors = {}
    doors[name] = topic

    lock = dlock13.Opener(doors)
    try:
        return lock.open(name, duration)
    except Exception, e:
        lock = None
        raise e

def main():
    prog, args = sys.argv[0], sys.argv[1:]

    if len(args) < 2:
        print 'Usage: dlock13-open mqtt/lock/prefix duration'
        return 1

    topic, duration = args
    duration = int(duration)
    until = open(topic, duration)
    print 'Door at %s is open for %d seconds' % (topic, int(until-time.time()))

if __name__ == '__main__':
    sys.exit(main())
