#!/bin/bash

set -e

check() {
  local key="$1"; shift

  local value="${!key}"

  if [[ -z $value ]]
  then
    echo "Missing environment variable $key"
    exit 1
  fi
}

check BROKER
check DOOR
check DELAY

opts+=(-h "$BROKER")
opts+=(-t "/bitraf/door/$DOOR/open")

if [[ ! -z $MQTT_USERNAME ]]
then
  opts+=(--username "$MQTT_USERNAME" --pw "$MQTT_PASSWORD")
fi

exec mosquitto_pub -d "${opts[@]}" -m "$DELAY"
