#!/bin/bash

set -e

check() {
  local key="$1"; shift

  local value="${!key}"

  if [[ -z $value ]]
  then
    echo "Missing environment variable $key"
    exit 1
  fi
}

check BROKER
check DOOR

opts=(-i "bitraf-door-$DOOR")
opts+=(-h "$BROKER")
opts+=(-t "bitraf/door/$DOOR/open")

if [[ ! -z $MQTT_USERNAME ]]
then
  opts+=(--username "$MQTT_USERNAME" --pw "$MQTT_PASSWORD")
fi

while true
do
  echo "Connecting to MQTT"
  mosquitto_sub "${opts[@]}" | while read delay rest_of_line
  do
    if bitraf-door-sanitize-delay "$delay" >/dev/null
    then
      echo "Opening door, delay=$delay"
      sleep "$delay"
      unlock
    fi
  done
  sleep 1
done
