#!/bin/bash

set -e

check() {
  local key="$1"; shift

  local value="${!key}"

  if [[ -z $value ]]
  then
    echo "Missing environment variable $key"
    exit 1
  fi
}

check BROKER
check DOOR

opts=()
opts+=(-h "$BROKER")
opts+=(-t "/bitraf/door/$DOOR/open")

if [[ ! -z $MQTT_USERNAME ]]
then
  opts+=(--username "$MQTT_USERNAME" --pw "$MQTT_PASSWORD")
fi

echo "Connecting to MQTT"
mosquitto_sub "${opts[@]}" | while read delay rest_of_line
do
  if bitraf-door-sanitize-delay "$delay" >/dev/null
  then
    echo "Opening door, delay=$delay"
    unlock &
  else
    echo "Bad delay value: $delay"
  fi
done
sleep 1
