#!/bin/bash

# test cases: ./bitraf-door-sanitize-delay a11230; ./bitraf-door-sanitize-delay 123; ./bitraf-door-sanitize-delay -10  ./bitraf-door-sanitize-delay 60;

re="^[[:digit:]]+$" 

if [[ ! ( $1 =~ $re ) ]]
then
  echo "fail, invalid number"
  exit 1
fi

if [[ $1 -gt 60 ]]
then
  echo "fail, too big"
  exit 1
fi

if [[ $1 -lt 0 ]]
then
  echo "fail, too small"
  exit 1
fi

echo "success"
exit 0
